// <auto-generated />
using LabTaskFinal.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LabTaskFinal.Migrations
{
    [DbContext(typeof(UMSContext))]
    [Migration("20251223071006_CtgPrAdded")]
    partial class CtgPrAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LabTaskFinal.EF.Table.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("LabTaskFinal.EF.Table.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("Pid")
                        .HasColumnType("int");

                    b.Property<int>("ctgId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ctgId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("LabTaskFinal.EF.Table.Product", b =>
                {
                    b.HasOne("LabTaskFinal.EF.Table.Category", "ctg")
                        .WithMany()
                        .HasForeignKey("ctgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ctg");
                });
#pragma warning restore 612, 618
        }
    }
}
